development:
  adapter: postgresql
  database: test_alexa
  username: alicjacyganiewicz
  password:
  port: 5432
  host: localhost
  encoding: unicode
  pool: 5
  allow_concurrency: true
  min_messages: error
production:
  adapter: postgresql
  database: test_alexa
  username: alicjacyganiewicz
  password: ~
  port: 5432
  host: localhost
  encoding: unicode
  pool: 5
  allow_concurrency: true
  min_messages: error
test:
  adapter: postgresql
  database: test_alexa_test
  username: alicjacyganiewicz
  password: ~
  port: 5432
  host: localhost
  encoding: unicode
  pool: 5
  allow_concurrency: true
  min_messages: error
